CREATE TABLE TB_USER
(
	USER_SEQ VARCHAR(40) PRIMARY KEY,
	USER_ID VARCHAR(20) UNIQUE KEY NOT NULL,
	USER_NAME VARCHAR(30) NOT NULL,
	EMAIL VARCHAR(30) NULL,
	USER_PWD VARCHAR(100) NOT NULL,
	USER_PWD_KEY VARCHAR(80) NOT NULL,
	USER_AUTH INT(2) NOT NULL,
	USE_YN CHAR(1) NOT NULL,
	REG_DATE DATETIME NOT NULL,
	UDT_DATE DATETIME NULL
)

CREATE TABLE TB_MENU
(
	MENU_SEQ VARCHAR(40) PRIMARY KEY,
	MENU_ID VARCHAR(20) UNIQUE KEY NOT NULL,
	MENU_NAME VARCHAR(30) NOT NULL,
	MENU_URL VARCHAR(100) NOT NULL,
	PARENT_MENU_SEQ VARCHAR(40) NULL,
	INST_ID VARCHAR(20) NOT NULL,
	INST_DATE DATETIME NOT NULL,
	UPDT_ID VARCHAR(20) NULL,
	UPDT_DATE DATETIME NULL
)

CREATE TABLE TB_BOARD
(
	BOARD_SEQ VARCHAR(40) PRIMARY KEY,
	TITLE VARCHAR(300) NOT NULL,
	CONTENT TEXT NULL,
	EXPLANATION VARCHAR(1000) NULL,
	MAIN_TOP_VIEW CHAR(1) NOT NULL,
	CATEGORY_ID VARCHAR(20) NOT NULL,
	INST_ID VARCHAR(20) NOT NULL,
	INST_DATE DATETIME NOT NULL,
	UPDT_ID VARCHAR(20) NULL,
	UPDT_DATE VARCHAR(20) NULL
)

CREATE TABLE TB_CATEGORY
(
	CATEGORY_SEQ VARCHAR(40) PRIMARY KEY,
	CATEGORY_ID VARCHAR(20) NOT NULL,
	CATEGORY_NAME VARCHAR(100) NOT NULL,
	MAIN_VIEW_AREA VARCHAR(20) NULL,
	INST_ID VARCHAR(20) NOT NULL,
	INST_DATE DATETIME NOT NULL
)

CREATE TABLE TB_FILE
(
	FILE_SEQ VARCHAR(40) PRIMARY KEY,
	BOARD_SEQ VARCHAR(40) NOT NULL,
	ORIGIN_FILE_NAME VARCHAR(200) NOT NULL,
	EXTENSION_NAME VARCHAR(10) NOT NULL,
	FILE_SIZE INT(100) NOT NULL,
	SAVE_FILE_NAME VARCHAR(200) NOT NULL,
	SAVE_FILE_PATH VARCHAR(300) NOT NULL,
	FILE_URL VARCHAR(100) NOT NULL,
	FILE_KIND VARCHAR(10) NOT NULL,
	INST_ID VARCHAR(20) NOT NULL,
	INST_DATE DATETIME NOT NULL
)

CREATE TABLE TB_COMMENT 
(
  TB_COMMENT_SEQ VARCHAR(100) NOT NULL,
  TB_COMMENT_NUM INT(100) PRIMARY KEY,
  TB_COMMENT_TITLE VARCHAR(50) NOT NULL,
  TB_COMMENT_COMMENT TEXT DEFAULT NULL,
  TB_COMMENT_REG_ID VARCHAR(100) NOT NULL,
  TB_COMMENT_REG_DATE DATE NOT NULL,
  TB_COMMENT_UDT_ID VARCHAR(100) DEFAULT NULL,
  TB_COMMENT_UDT_DATE DATE DEFAULT NULL
)